# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: java-format
        name: java-format
        entry: ./tools/fix_java_format.sh --replace
        language: script
        files: '\.java$'
        require_serial: true
        pass_filenames: true
      - id: buildifier
        name: buildifier
        entry: bazel --noblock_for_lock run //:buildifier.fix
        language: system
        require_serial: true
        pass_filenames: false # this is a global check, only run it once
      - id: validate-grammar-rules
        name: validate-grammar-rules
        entry: ./tools/validate_grammar_rules.py --changed-only
        language: python
        files: '\.g4$'
        require_serial: true
        pass_filenames: true
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args:
          [
            "--in-place",
            "--remove-all-unused-imports",
            "--remove-unused-variables",
          ]
